# This file should never be checked into version control.
# In order to generate the secrets, do the following.
#   1. Modify below values as needed
#   2. Run `sops -e --gcp-kms projects/staging-nl/locations/global/keyRings/sops/cryptoKeys/sopskey1 --encrypted-regex '^(data|stringData)$' secrets.example.yaml > secrets.yaml
#   3. Run `rm secrets.example.yaml`
#   4. (To recover) Run `sops -d secrets.yaml > secrets.plain.yaml`
#   5. Check `git status` and verify no plain-text file is added or committed
apiVersion: v1
type: Opaque
kind: Secret
metadata:
    name: postgres-<%my-service%>-secrets
    namespace: default
stringData:
    POSTGRES_PASSWORD: <%redacted%> # WARNING!!! READ HEADER
