---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insight-engine
spec:
  template:
    spec:
      containers:
        - name: insight-engine
          env:
            - name: FRAUDIO_GCP_REGION
              value: europe-west4
            - name: INSIGHT_ENGINE_FRAUDIO_KAFKA_SERVERS
              value: kafka-nl-fraudio-8ea0.aivencloud.com:10796
            - name: INSIGHT_ENGINE_FRAUDIO_KAFKA_SCHEMA_REGISTRY_URL
              value: https://{user}:{pw}@kafka-nl-fraudio-8ea0.aivencloud.com:10799
