---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <%my-service%>
spec:
  template:
    spec:
      containers:
        - name: <%my-service%>
          env:
            - name: FRAUDIO_GCP_REGION
              value: asia-south1
            - name: <%MY_SERVICE%>_FRAUDIO_KAFKA_SERVERS
              value: kafka-asia-south1-fraudio-prd-gcp-asia-south1.i.aivencloud.com:26651
            - name: <%MY_SERVICE%>_FRAUDIO_KAFKA_SCHEMA_REGISTRY_URL
              value: https://{user}:{pw}@kafka-asia-south1-fraudio-prd-gcp-asia-south1.i.aivencloud.com:26654
            - name: <%MY_SERVICE%>_FRAUDIO_POSTGRES_HOST
              value: pg-auth-db-asia-south1-fraudio-prd-gcp-asia-south1.f.aivencloud.com
            - name: <%MY_SERVICE%>_FRAUDIO_POSTGRES_PORT
              value: "26649"
