---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insight-engine
  labels:
    app.kubernetes.io/component: insight-engine
    app.kubernetes.io/part-of: fraudio
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: insight-engine
  template:
    metadata:
      labels:
        app: insight-engine
    spec:
      volumes:
        - name: kafka-auto-credential-stores
          secret:
            secretName: kafka-insight-engine-secrets
      containers:
        - name: insight-engine
          image: registry.gitlab.com/fraudio/insight-engine:${CICD_IMAGE_VERSION}
          imagePullPolicy: Always
          env:
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: kafka-insight-engine-secrets
                  key: HOST

            - name: KAFKA_PORT
              valueFrom:
                secretKeyRef:
                  name: kafka-insight-engine-secrets
                  key: PORT
            - name: INSIGHT_ENGINE_FRAUDIO_KAFKA_SCHEMA_REGISTRY_USER
              valueFrom:
                secretKeyRef:
                  name: kafka-insight-engine-secrets
                  key: USER
            - name: INSIGHT_ENGINE_FRAUDIO_KAFKA_SCHEMA_REGISTRY_PASS
              valueFrom:
                secretKeyRef:
                  name: kafka-insight-engine-secrets
                  key: USER_PASS
            - name: OTEL_SERVICE_NAME
              value: insight-engine
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_TRACES_EXPORTER
              value: "none" # otlp
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://grafana-k8s-monitoring-alloy.monitoring.svc.cluster.local:4317"
            - name: OTEL_TRACES_SAMPLER
              value: "always_off" # "parentbased_traceidratio"
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1.0"
            - name: INSIGHT_ENGINE_RUNNING_ON_GCLOUD
              value: "true"
          resources:
            requests:
              memory: 150Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: "1"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: kafka-auto-credential-stores
              mountPath: "/root/.tls/insight-engine-kafka"
              readOnly: true
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 1
      imagePullSecrets:
        - name: registry.gitlab.com
