---
apiVersion: v1
kind: Service
metadata:
  name: insight-engine
  labels:
    app.kubernetes.io/component: insight-engine
    app.kubernetes.io/part-of: fraudio
spec:
  selector:
    app: insight-engine
  ports:
    - name: http
      port: 8080
      targetPort: 8080
