fraudio_env_display_name: None
default_log_level: INFO
default_app_log_level: INFO
file_log_level: NOTSET
hot_reload: false
openapi_ui: false
log_stacktraces_http_500: true
tracing_enabled: true
running_on_gcloud: false
fraudio_kafka_enabled: false
fraudio_kafka_producer_timeout_in_seconds: 60
fraudio_kafka_servers: [ 'localhost:9092' ]
fraudio_kafka_schema_registry_url: 'http://localhost:8081'
fraudio_kafka_schema_registry_user: localuser
fraudio_kafka_schema_registry_pass: localpass
fraudio_kafka_secrets_path: '~/.tls/local-kafka'
